# Generated by Django 2.2.3 on 2019-08-28 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_auto_20190828_0306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='addess_type',
            new_name='address_type',
        ),
    ]
